### ISSUE TITLE
Is it possible to add additional domains to a created site

### ISSUE THREAD

**Issue by benlk** [10up/wp-local-docker-v2#195]
I have a site, `example.test`, which is a local development clone of the production site, `example.com`. There is some third-party code which runs on pages on this site, which I'd like to test. Unfortunately, this third-party code needs to be running on a webpage with the production domain name, `example.com`.

What I'd like to do is temporarily add `example.com` to the list of domain names that route to this site's container.

I've tried:
- adding `example.com` to `/etc/hosts` in the same place as `example.test`, pointing to the same IP address: Chrome shows an `ERR_CONNECTION_CLOSED` "this site can't be reached" error.
    - This is true whether using `vim` to add the entry to `/etc/hosts` or using `sudo 10updocker-hosts add example.com`
- adding `example.com` and `*.example.com` to `docker-compose.yml` and rebooting the container: Chrome shows an `ERR_CONNECTION_CLOSED` "this site can't be reached" error.
- adding `example.com` to `.config.json` (in the dame directory as `docker-compose.yml`) and rebooting the container: Chrome shows an `ERR_CONNECTION_CLOSED` "this site can't be reached" error.

I've done this in Laravel Valet before without too much trouble; I was wondering whether it'd be possible to do this in 10up's docker environment.

```
10updocker --version: 2.8.1
docker --version: Docker version 20.10.5, build 55c4c88
Chrome version: 89
MacOS: 10.15
```

**Comment by dustinrue** [comment]
Yes, edit the docker-compose.yml file and edit the VIRTUAL_HOST value

**Comment by benlk** [comment]
Like this?
```
 nginx:
   image: 'nginx:latest'
   expose:
     - '80'
     - '443'
   volumes:
     - './wordpress:/var/www/html:cached'
     - './config/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached'
   depends_on:
     - phpfpm
   networks:
     - default
     - wplocaldocker
   environment:
     CERT_NAME: localhost
     HTTPS_METHOD: noredirect
     VIRTUAL_HOST: 'example.test,*.example.test,example.com,*.example.com'
```

I did that and restarted Docker several times; Chrome was never able to open a connection.
