### ISSUE TITLE
docker-compose deprecated args

### ISSUE THREAD

**Issue by pabamato** [10up/wp-local-docker-v2#274]
**Is your enhancement related to a problem? Please describe.**
Getting a deprecated message related to the docker-compose file

The docker-compose.yml file has the following:
```
networks:
  wplocaldocker:
    external:
      name: wplocaldocker
volumes:
  wplocaldockerCache:
    external:
      name: wplocaldockerCache
```
**Describe the solution you'd like**

Update the syntaxis as per the official docs:
https://docs.docker.com/compose/networking/#use-a-pre-existing-network
```
networks:
  wplocaldocker:
    external: true
    name: wplocaldocker
volumes:
  wplocaldockerCache:
    external: true
    name: wplocaldockerCache
```

**Additional context**
Getting a deprecated message when running a wp-cli command:
![image](https://user-images.githubusercontent.com/4009928/148422803-ad4551a6-21f3-44f6-b85c-77daa37a3f9a.png)
